version: '3.5'

services:

  vault-compose:
    image: vault:0.9.6
    build:
      context: ./vault
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=myroot 
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - postgres-vault-network

  postgres-compose:
    image: postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
    networks:
      - postgres-vault-network

networks:
  postgres-vault-network:
    driver: bridge
